### ISSUE TITLE
Add read-only mode support

### ISSUE THREAD

**Issue by brc-dd** [kommitters/editorjs-drag-drop#13]
Recent EditorJS version has included a property `readOnly`. [Ref.](https://editorjs.io/configuration#read-only-mode)

The suggested approach in README (creating new instance of class inside onReady) throws an exception (`Unhandled Rejection (TypeError): Cannot read property 'setAttribute' of null`), when used with `readOnly: true`.

It is possible to determine if readOnly is being passed to the editor _**internally**_?

The current workaround is simple: just add the object instantiation inside something like a `if (!readOnly)` block. But it will be nice if DragDrop can implicitly handle this.

**Comment by juanhurtado10** [comment]
Merged in #22
