### ISSUE TITLE
feature: Be able to use drag and drop ontable rows

### ISSUE THREAD

**Issue by Aarbel** [kommitters/editorjs-drag-drop#144]
cf https://github.com/editor-js/table/issues/147

Is this library working to change table rows / columns order ?

Thanks a lot for your help

cc [MarioRodriguezS](https://github.com/MarioRodriguezS)

**Comment by ValenMorales** [comment]
Hi @Aarbel,

After reviewing the request, we’ve found that integrating this feature directly into the table block would be a more effective solution than incorporating it into the drag-and-drop plugin. This approach is likely to provide a more consistent experience for managing table functionalities, as tables operate as distinct, standalone blocks.
