### ISSUE TITLE
setAttribute fires before editor is ready

### ISSUE THREAD

**Issue by papppeter** [kommitters/editorjs-drag-drop#148]
### Precheck

- [x] Do a quick search and make sure the bug has not been reported yet.
- [x] Please disclose security vulnerabilities privately at [oss@kommit.co](mailto:oss@kommit.co).
- [x] Finally, be nice and have fun!.

### Description

First of all thanks for the plugin!

I have a strage behavior with the newest editorjs. Locally, and in live environment everything works as expected. 

But in my test suit on github action says editor is not ready. 

We are running tests with cypress. 
Cypress tests are passing locally.
Cypress tests are failing in github actions.

"     TypeError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.

  > Cannot read properties of null (reading 'setAttribute')"

i know it is not really informative, but i discovered if i delay DragDrop initalization then the error disapiers.

for now i use following code inside isReady promise:

  setTimeout(() => {
    new DragDrop(editor);
  }, 250);

### Environment

* Editor.js version: 2.30.4
* Plugins you use with their versions:
* Device, Browser, OS: ubuntu, chromium, github ci

### Current behavior

we get error: Cannot read properties of null (reading 'setAttribute') 
not all the time.

### Expected behavior

no error happens

### Additional context

issue happens only in github action tests with cypress.
it did worked before we switched to v2.30

**Comment by ValenMorales** [comment]
Hi, @papppeter 
I wanted to let you know that in the latest release of the plugin, the bug you reported has been resolved, please feel free to update to the latest version and let us know if you experience any further issues.

**Comment by papppeter** [comment]
thanks for a quick fix! i will test in our app.

**Comment by papppeter** [comment]
@ValenMorales unfortunately we still have the same issue. 

I cannot recrate it locally only in CI.
