### ISSUE TITLE
handle button is 200 px above the cursor

### ISSUE THREAD

**Issue by lhapaipai** [kommitters/editorjs-drag-drop#15]
Hi,
Thanks a lot for your plugin !

I have an issue with the handle button (four squares) when i drag a block. when I click on the button he appear 200px above the cursor.
![handle](https://user-images.githubusercontent.com/1088155/104957282-242d0f80-59ce-11eb-9a52-8219e3ac9884.gif)

editorjs-drag-drop : 0.1.1
@editorjs/editorjs : 2.19.1

good night !

**Comment by juanhurtado10** [comment]
Hello, @lhapaipai thanks for reaching out, and sorry for the late response. Were you able to solve the issue? I have given it a try and seems working fine. Maybe an overlapping CSS? 

Best!
