### ISSUE TITLE
Why the axios package is in dependencies for that plugin?

### ISSUE THREAD

**Issue by Oyshoboy** [kommitters/editorjs-drag-drop#19]
Hi, npm audit found a [high vulnerability ](https://www.npmjs.com/advisories/1594) for axios package, and don't understand, why this package is in dependencies for drag-drop plugin?

**Comment by juanhurtado10** [comment]
@Oyshoboy thanks for reporting. You're definitely right, there is no room for that dependency. Scheduled to be removed on the next release.
