### ISSUE TITLE
Dragging the only block in the editor above itself causes EditorJS to be broken

### ISSUE THREAD

**Issue by rster2002** [kommitters/editorjs-drag-drop#56]
### Precheck

- [X] Do a quick search and make sure the bug has not been reported yet.
- [X] Please disclose security vulnerabilities privately at [oss@kommit.co](mailto:oss@kommit.co).
- [X] Finally, be nice and have fun!.

### Description

When there is only one block in the editor you can drag a block above itself. Doing this will break the editor. It seems it you move the block out of an array, but I'm not sure.

![Screenshot 2021-12-06 at 13 34 53](https://user-images.githubusercontent.com/26026518/144846986-5bd51e04-96c6-4764-8cd3-b0af547f783d.png)

### Environment

* Editor.js version: 2.19.3
* Plugins you use with their versions: 
  * `@editorjs/header`: 2.6.2
  * `editorjs-drag-drop`: 1.0.0
* Device, Browser, OS: Chrome 96.0.4664.55 (Official Build) (arm64), macOS Version 12.0.1 (Build 21A559)

### Current behavior (steps to reproduce)

* Create a new EditorJs instance and add the drag-and-drop plugin as described in the readme (without undo plugin)
* Create a paragraph block
* Drag the block until you see and indicator appear above the block and drop it
* The editor is now broken.

### Expected behavior

You shouldn't be able to move a block when there is only one present.

### Additional context

When there is more than one block in the editor the drag-and-drop works as expected.

**Comment by MarioRodriguezS** [comment]
@rster2002 Hi there!
Thanks a lot for report the issue,
It was solved, and the solution will be updated in our v1.0.1 soon.

Best,
Mario

**Comment by rster2002** [comment]
Thanks a lot for your time!
