### ISSUE TITLE
During multiple drag and drop processes, part of the text will be lost

### ISSUE THREAD

**Issue by chenguzhen87** [kommitters/editorjs-drag-drop#75]
### Precheck

- [ ] Do a quick search and make sure the bug has not been reported yet.
- [ ] Please disclose security vulnerabilities privately at [oss@kommit.co](mailto:oss@kommit.co).
- [ ] Finally, be nice and have fun!.

### Environment

* Editor.js version:
* Plugins you use with their versions:
* Device, Browser, OS:

### Current behavior

Include code samples, errors and stack traces if appropriate.
If reporting a bug, please include the reproducing steps.

**Comment by santiagoboterokommit** [comment]
@chenguzhen87 Thanks for the report, A new version was released to solve this issue in a proper way (v1.1.2)
