### ISSUE TITLE
Drag and Drop removes last character every time it's used

### ISSUE THREAD

**Issue by christoph-kluge** [kommitters/editorjs-drag-drop#79]
### Precheck

- [x] Do a quick search and make sure the bug has not been reported yet.
- [x] Please disclose security vulnerabilities privately at [oss@kommit.co](mailto:oss@kommit.co).
- [x] Finally, be nice and have fun!.

### Description

If I Drag and Drop all the time then the behavior removes the last characters of the headline.

### Environment

* Editor.js version: 2.24.2
* Plugins you use with their versions:
* Device, Browser, OS: Moneterey 12.3 - Safari - Version 15.4 (17613.1.17.1.6)

### Current behavior

See video

### Additional context

https://user-images.githubusercontent.com/1446269/166200599-0ec786a6-0b5e-42ee-8052-8bdb66105a13.mov

**Comment by christoph-kluge** [comment]
Duplicate of #75 but with video :-)

**Comment by santiagoboterokommit** [comment]
@christoph-kluge Thank you for your report, it is solved and published in npm (1.1.1)

**Comment by christoph-kluge** [comment]
@santiagoboterokommit thank you. It works like a breeze now! 

I assume #75 can be closed as well since it was a duplicate of this report.
