### ISSUE TITLE
Header drag and drop leaves a blank header block.

### ISSUE THREAD

**Issue by Sesi0** [kommitters/editorjs-drag-drop#8]
When I highlight the whole header block and drag and drop it elsewhere it leaves a blank header block in the old position,
Here is a demo:

Test 1:
![editor-1](https://user-images.githubusercontent.com/10748411/101465718-f7a2c400-3948-11eb-8f2a-0b6db889d19e.gif)

Test 2:
![editor-2](https://user-images.githubusercontent.com/10748411/101465486-adb9de00-3948-11eb-87cd-8cc1e12769b3.gif)

I thought it is my mistake but I tried it in some other opensource projects which use editorjs and this plugin and it behaves the same..

**Comment by MarioRodriguezS** [comment]
@Sesi0 Thanks for your comment. As you can see in the Readme file, the plugin works when you drag and drop blocks from the 'settings' button located on the right side of the block, I recommend you to see the gif in the Readme file. So when you use the plugin as in the Readme file you will not have any problem when you drag a block, it will be dropped without any blank block.  
Best,
Mario
