### ISSUE TITLE
CTRL+Z does not behave as expected.

### ISSUE THREAD

**Issue by Sesi0** [kommitters/editorjs-drag-drop#9]
When a part of the text is dragged to another position and CTRL+Z is pressed it makes a duplication.

Here is a demo:
![N4Cd4aCJQN](https://user-images.githubusercontent.com/10748411/101469626-a9dc8a80-394d-11eb-9643-93e3853515f3.gif)

I installed the editorjs-undo plugin but it behaves the same.

**Comment by MarioRodriguezS** [comment]
@Sesi0 Thanks for your comment. As you can see in the Readme file, the plugin works when you drag and drop blocks, and the idea is to drag the blocks from the 'settings' button located on the right side of the block, I recommend you to see the gif in the Readme file.  So when you use the plugin as in the Readme file you will not have any problem with the Ctrl+Z action, you can use the [editorjs-undo](https://github.com/kommitters/editorjs-undo) as well.
Best, 
Mario
